export * from './randomHexColor';
export * from './isTabActive';
export * from './elementIsInFocus';
export * from './judgeDeviceType';
export * from './copyText';
export * from './getSelectedText';
export * from './rgbToHex';
export * from './toCamel';
export * from './smoothScroll';
