export { isEmpty } from './isEmpty';
export * from './isNumber';
export * from './isString';
export * from './isObject';
export * from './isNull';
export * from './isArray';
export * from './isUndefined';
export * from './isTrue';
export * from './isElement';
export * from './getTypeOf';
