# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy websit with GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run:  |
          npm install
          npm run docs:build

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Vuepress deploy
        # You may pin to the exact commit or the version.
        # uses: jenkey2011/vuepress-deploy@c125854a55a2d3fbe1847e0fc25a4aa662582520
        uses: jenkey2011/vuepress-deploy@v1.8.1
